SELECT * FROM [Person].[Person];
SELECT * FROM [Person].[Address];
SELECT * FROM [Person].[StateProvince];
SELECT * FROM [HumanResources].[Department];
SELECT * FROM Person.PersonPhone;
SELECT * FROM [Person].[PhoneNumberType];
SELECT * FROM [Person].[AddressType];
SELECT * FROM [Person].[EmailAddress]
SELECT * FROM [Person].[Password]
SELECT * FROM [HumanResources].[Employee]
SELECT * FROM [HumanResources].[Department]
SELECT * FROM [HumanResources].[EmployeeDepartmentHistory]
SELECT * FROM [HumanResources].[EmployeePayHistory]
